# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AFSSLTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AFSSLTest
pod 'AFNetworking', '~> 3.2.1'
  target 'AFSSLTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFSSLTestUITests' do
    # Pods for testing
  end

end
